Repository Chemaclass/typed-arrays, pull requests merged in 2021-03, with the labels that each got.

#11 When adding elements to an ArrayOf already instantiated, the typeToEn…
  src/AbstractArrayOf.php
  src/Exceptions/InvalidInstantiationType.php
  src/Exceptions/InvalidTypeException.php
  src/Exceptions/ListException.php
  tests/Unit/Scalars/ArrayOfBooleanTest.php
  tests/Unit/Scalars/ArrayOfFloatTest.php
  tests/Unit/Scalars/ArrayOfIntegerTest.php
  tests/Unit/Scalars/ArrayOfStringTest.php
Labels: bug

#13 Replace ArrayOf to TypedArrays
  README.md
  composer.json
  example/index.php
  src/AbstractTypedArray.php
  src/Decorators/MakeImmutable.php
  src/Decorators/MakeList.php
  src/Exceptions/ImmutabilityException.php
  src/Exceptions/InvalidSetupException.php
  src/Exceptions/InvalidTypeException.php
  src/Exceptions/ListException.php
  src/Scalars/TypedArrayBoolean.php
  src/Scalars/TypedArrayFloat.php
  src/Scalars/TypedArrayInteger.php
  src/Scalars/TypedArrayString.php
  tests/Unit/Fixtures/ArrayOfSimpleObjects.php
  tests/Unit/Fixtures/ImmutableTypedArraySimpleObjects.php
  tests/Unit/Fixtures/ListOfString.php
  tests/Unit/Fixtures/SimpleObject.php
  tests/Unit/Fixtures/TypedArraySimpleObjects.php
  tests/Unit/ImmutabilityTest.php
  tests/Unit/ListTest.php
  tests/Unit/Scalars/TypedArrayBooleanTest.php
  tests/Unit/Scalars/TypedArrayFloatTest.php
  tests/Unit/Scalars/TypedArrayIntegerTest.php
  tests/Unit/Scalars/TypedArrayStringTest.php
  tests/Unit/TypedArrayTest.php
Labels: enhancement, refactoring

#14 Add map type collections
  example/index.php
  src/AbstractTypedArray.php
  src/Decorators/MakeImmutable.php
  src/Decorators/MakeList.php
  src/Exceptions/MapException.php
  tests/Unit/Fixtures/MapOfString.php
  tests/Unit/ListTest.php
  tests/Unit/MapTest.php
Labels: enhancement, refactoring

#15 24 predefined collections
  .php_cs.dist
  example/index.php
  src/AbstractTypedArray.php
  src/Scalars/ImmutableBooleanArray.php
  src/Scalars/ImmutableBooleanList.php
  src/Scalars/ImmutableBooleanMap.php
  src/Scalars/ImmutableFloatArray.php
  src/Scalars/ImmutableFloatList.php
  src/Scalars/ImmutableFloatMap.php
  src/Scalars/ImmutableIntegerArray.php
  src/Scalars/ImmutableIntegerList.php
  src/Scalars/ImmutableIntegerMap.php
  src/Scalars/ImmutableStringArray.php
  src/Scalars/ImmutableStringList.php
  src/Scalars/ImmutableStringMap.php
  src/Scalars/MutableBooleanArray.php
  src/Scalars/MutableBooleanList.php
  src/Scalars/MutableBooleanMap.php
  src/Scalars/MutableFloatArray.php
  src/Scalars/MutableFloatList.php
  src/Scalars/MutableFloatMap.php
  src/Scalars/MutableIntegerArray.php
  src/Scalars/MutableIntegerList.php
  src/Scalars/MutableIntegerMap.php
  src/Scalars/MutableStringArray.php
  src/Scalars/MutableStringList.php
  src/Scalars/MutableStringMap.php
  tests/Unit/Fixtures/ImmutableSimpleObjectArray.php
  tests/Unit/Fixtures/MutableSimpleObjectList.php
  tests/Unit/Fixtures/MutableSimpleObjectMap.php
  tests/Unit/ImmutabilityTest.php
  tests/Unit/ListTest.php
  tests/Unit/MapTest.php
  tests/Unit/Scalars/ImmutableBooleanArrayTest.php
  tests/Unit/Scalars/ImmutableBooleanListTest.php
  tests/Unit/Scalars/ImmutableBooleanMapTest.php
  tests/Unit/Scalars/ImmutableFloatArrayTest.php
  tests/Unit/Scalars/ImmutableFloatListTest.php
  tests/Unit/Scalars/ImmutableFloatMapTest.php
  tests/Unit/Scalars/ImmutableIntegerArrayTest.php
  tests/Unit/Scalars/ImmutableIntegerListTest.php
  tests/Unit/Scalars/ImmutableIntegerMapTest.php
  tests/Unit/Scalars/ImmutableStringArrayTest.php
  tests/Unit/Scalars/ImmutableStringListTest.php
  tests/Unit/Scalars/ImmutableStringMapTest.php
  tests/Unit/Scalars/MutableBooleanArrayTest.php
  tests/Unit/Scalars/MutableBooleanListTest.php
  tests/Unit/Scalars/MutableBooleanMapTest.php
  tests/Unit/Scalars/MutableFloatArrayTest.php
  tests/Unit/Scalars/MutableFloatListTest.php
  tests/Unit/Scalars/MutableFloatMapTest.php
  tests/Unit/Scalars/MutableIntegerArrayTest.php
  tests/Unit/Scalars/MutableIntegerListTest.php
  tests/Unit/Scalars/MutableIntegerMapTest.php
  tests/Unit/Scalars/MutableStringArrayTest.php
  tests/Unit/Scalars/MutableStringListTest.php
  tests/Unit/Scalars/MutableStringMapTest.php
  tests/Unit/TypedArrayTest.php
Labels: enhancement

#16 Place dataProviders() next to the function which is calling it
  tests/Unit/Fixtures/SimpleObject.php
  tests/Unit/Scalars/ImmutableBooleanArrayTest.php
  tests/Unit/Scalars/ImmutableBooleanListTest.php
  tests/Unit/Scalars/ImmutableBooleanMapTest.php
  tests/Unit/Scalars/ImmutableFloatArrayTest.php
  tests/Unit/Scalars/ImmutableFloatListTest.php
  tests/Unit/Scalars/ImmutableFloatMapTest.php
  tests/Unit/Scalars/ImmutableIntegerArrayTest.php
  tests/Unit/Scalars/ImmutableIntegerListTest.php
  tests/Unit/Scalars/ImmutableIntegerMapTest.php
  tests/Unit/Scalars/ImmutableStringArrayTest.php
  tests/Unit/Scalars/ImmutableStringListTest.php
  tests/Unit/Scalars/ImmutableStringMapTest.php
  tests/Unit/Scalars/MutableBooleanArrayTest.php
  tests/Unit/Scalars/MutableBooleanListTest.php
  tests/Unit/Scalars/MutableBooleanMapTest.php
  tests/Unit/Scalars/MutableFloatArrayTest.php
  tests/Unit/Scalars/MutableFloatListTest.php
  tests/Unit/Scalars/MutableFloatMapTest.php
  tests/Unit/Scalars/MutableIntegerArrayTest.php
  tests/Unit/Scalars/MutableIntegerListTest.php
  tests/Unit/Scalars/MutableIntegerMapTest.php
  tests/Unit/Scalars/MutableStringArrayTest.php
  tests/Unit/Scalars/MutableStringListTest.php
  tests/Unit/Scalars/MutableStringMapTest.php
Labels: refactoring

#19 Add some basic docu
  README.md
Labels: documentation

#20 Add a more complex example of how to make a matrix with our library
  .php_cs.dist
  example/articles.php
  example/int_matrix.php
  example/interface_publications.php
Labels: documentation

#21 Fix the link from the README file in Working example section
  README.md
Labels: documentation

#25 Combine some exceptions into GuardException
  example/int_matrix.php
  src/AbstractTypedArray.php
  src/Exceptions/GuardException.php
  src/Exceptions/ImmutabilityException.php
  src/Exceptions/InvalidSetupException.php
  src/Exceptions/ListException.php
  src/Exceptions/MapException.php
  tests/Unit/ImmutabilityTest.php
  tests/Unit/ListTest.php
  tests/Unit/MapTest.php
  tests/Unit/Scalars/ImmutableBooleanArrayTest.php
  tests/Unit/Scalars/ImmutableBooleanListTest.php
  tests/Unit/Scalars/ImmutableBooleanMapTest.php
  tests/Unit/Scalars/ImmutableFloatArrayTest.php
  tests/Unit/Scalars/ImmutableFloatListTest.php
  tests/Unit/Scalars/ImmutableFloatMapTest.php
  tests/Unit/Scalars/ImmutableIntegerArrayTest.php
  tests/Unit/Scalars/ImmutableIntegerListTest.php
  tests/Unit/Scalars/ImmutableIntegerMapTest.php
  tests/Unit/Scalars/ImmutableStringArrayTest.php
  tests/Unit/Scalars/ImmutableStringListTest.php
  tests/Unit/Scalars/ImmutableStringMapTest.php
  tests/Unit/Scalars/MutableBooleanListTest.php
  tests/Unit/Scalars/MutableBooleanMapTest.php
  tests/Unit/Scalars/MutableFloatListTest.php
  tests/Unit/Scalars/MutableFloatMapTest.php
  tests/Unit/Scalars/MutableIntegerListTest.php
  tests/Unit/Scalars/MutableIntegerMapTest.php
  tests/Unit/Scalars/MutableStringListTest.php
  tests/Unit/Scalars/MutableStringMapTest.php
  tests/Unit/TypedArrayTest.php
Labels: refactoring

#24 #23 - Allow nullable elements in a collection
  README.md
  example/articles.php
  example/translations.php
  src/AbstractTypedArray.php
  tests/Unit/Fixtures/NonNullableSimpleObjectArray.php
  tests/Unit/Fixtures/NullableSimpleObjectArray.php
  tests/Unit/NullabilityTest.php
  tests/Unit/TypedArrayTest.php
Labels: documentation, enhancement
